[package]
name = "types"
version = "0.1.0"
edition = "2018"
autobins = false

[features]
default = []

[dependencies.differential_datalog]
path = "../differential_datalog"

[dependencies]
abomonation = "0.7"
ordered-float = { version = "2.0.0", features = ["serde"] }
time = { version = "0.2", features = ["serde"] }
differential-dataflow = "0.11.0"
fnv = "1.0.2"
once_cell = "1.4.1"
libc = "0.2"
num-traits = "0.2"
num = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
timely = "0.11"
erased-serde = "0.3"

[lib]
name = "types"
path = "lib.rs"


[dependencies.rslint_core]
path = "../../../rslint_core"
version = "0.2.2"

[dependencies.arc-interner]
version = "0.1"
