bench = []
bin = []
example = []
test = []
[badges.maintenance]
status = "none"

[build-dependencies]

[dependencies]
abomonation = "0.7"
differential-dataflow = "0.11.0"
erased-serde = "0.3"
fnv = "1.0.2"
libc = "0.2"
num = "0.3"
num-traits = "0.2"
once_cell = "1.4.1"
serde_json = "1.0"
timely = "0.11"

[dependencies.arc-interner]
features = []
optional = false
version = "0.1"

[dependencies.differential_datalog]
features = []
optional = false
path = "../differential_datalog"

[dependencies.ordered-float]
features = ["serde"]
optional = false
version = "2.0.0"

[dependencies.rslint_errors]
features = []
optional = false
path = "../../../rslint_errors"
version = "0.1.2"

[dependencies.rslint_parser]
features = []
optional = false
path = "../../../rslint_parser"
version = "0.2.1"

[dependencies.serde]
features = ["derive"]
optional = false
version = "1.0"

[dependencies.time]
features = ["serde"]
optional = false
version = "0.2"

[dev-dependencies]

[features]
c_api = ["differential_datalog/c_api"]
default = []

[lib]
bench = true
crate-type = ["lib"]
doc = true
doctest = true
harness = true
name = "types"
path = "lib.rs"
plugin = false
proc-macro = false
required-features = []
test = true

[package]
authors = []
autobenches = true
autobins = false
autoexamples = true
autotests = true
categories = []
edition = "2018"
keywords = []
name = "types"
publish = true
version = "0.1.0"

[patch]


[target]
