[package]
name = "rslint_scope"
version = "0.1.0"
authors = ["RSLint developers"]
edition = "2018"
license = "MIT"
description = "Scope analysis of JS programs"

[dependencies]
rslint_core = { path = "../rslint_core", version = "0.2.2" }
types = { path = "./generated/types" }
differential_datalog = { path = "./generated/differential_datalog" }
serde = { version = "1.0.115", features = ["derive"] }
typetag = "0.1.5"

[dependencies.rslint_scoping]
path = "./generated"
default-features = false
